name: alpha_scribex
description: An AI-powered writing app for high school students.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # UI packages
  flutter_svg: ^2.0.9
  loading_animation_widget: ^1.2.0+4

  # State management
  provider: ^6.1.1

  # iOS style icons
  cupertino_icons: ^1.0.2

  # Project features
  flutter_quill: ^10.8.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.2.2
  url_launcher: ^6.2.5
  quill_native_bridge: ^0.1.0
  flutter_keyboard_visibility: ^6.0.0

  # Voice input and AI
  speech_to_text: ^6.5.1
  http: ^1.1.0
  permission_handler: ^11.3.0 